### ISSUE TITLE
Questions about the used SMPL models

### ISSUE THREAD

**Issue by dulucas** [KlabCMU/UniversalHumanoidControl#1]
Hi, thanks for sharing your code! Great work!

BTW, I have some questions about the .xml SMPL models that you shared [here](https://github.com/KlabCMU/UniversalHumanoidControl/tree/master/assets/mujoco_models). I noticed that the positions of joints in the humanoid_smpl_neutral_mesh.xml and humanoid_smpl_neutral.xml are different. And after checking with SMPL's original model, it seems that the joint positions in humanoid_smpl_neutral_mesh.xml is aligned with original SMPL model while humanoid_smpl_neutral.xml is not. I also noticed that in [another repo](https://github.com/KlabCMU/kin-poly), you use the humanoid_smpl_neutral_mesh.xml for training. So if I understand correctly, if I want to use the SMPL model to train on AMASS dataset, I need to use humanoid_smpl_neutral_mesh.xml instead of humanoid_smpl_neutral.xml right? Besides, I'm curious about how did you get the humanoid_smpl_neutral_mesh.xml and what does the humanoid_smpl_neutral.xml aim for?

Hope to hear from you.

**Comment by ZhengyiLuo** [comment]
Hi! Thanks for the question. 

The neutral_mesh model is the correct one, while the humanoid_smpl_neutral.xml is a part of the developmental code that I haven't gotten around to removing; sorry about that! I will begin finishing up this repo shortly. 

To answer your question, [this file](https://github.com/KlabCMU/UniversalHumanoidControl/blob/master/uhc/smpllib/smpl_robot.py) contains the code to automatically generate meshed SMPL models in Mujoco with shape support.
